name: Build Default image
on:
  workflow_dispatch:
  push:
    paths:
      - containers/default/Dockerfile
      - containers/default/requirements.txt
      - .github/workflows/default.yml # Self-trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: netlab-cluster/default
  VERSION: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          build-mount-path: '/var/lib/docker'
      - name: Restart docker
        run: sudo service docker restart
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: containers/default
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
